convert bottom-active.xpm -resize 75% bottom-active.xpm
convert bottom-inactive.xpm -resize 75% bottom-inactive.xpm
convert bottom-left-active.xpm -resize 75% bottom-left-active.xpm
convert bottom-left-inactive.xpm -resize 75% bottom-left-inactive.xpm
convert bottom-right-active.xpm -resize 75% bottom-right-active.xpm
convert bottom-right-inactive.xpm -resize 75% bottom-right-inactive.xpm
convert close-active.xpm -resize 75% close-active.xpm
convert close-inactive.xpm -resize 75% close-inactive.xpm
convert close-pressed.xpm -resize 75% close-pressed.xpm
convert hide-active.xpm -resize 75% hide-active.xpm
convert hide-inactive.xpm -resize 75% hide-inactive.xpm
convert hide-pressed.xpm -resize 75% hide-pressed.xpm
convert left-active.xpm -resize 75% left-active.xpm
convert left-inactive.xpm -resize 75% left-inactive.xpm
convert maximize-active.xpm -resize 75% maximize-active.xpm
convert maximize-inactive.xpm -resize 75% maximize-inactive.xpm
convert maximize-pressed.xpm -resize 75% maximize-pressed.xpm
convert right-active.xpm -resize 75% right-active.xpm
convert right-inactive.xpm -resize 75% right-inactive.xpm
convert title-1-active.xpm -resize 75% title-1-active.xpm
convert title-1-inactive.xpm -resize 75% title-1-inactive.xpm
convert title-2-active.xpm -resize 75% title-2-active.xpm
convert title-2-inactive.xpm -resize 75% title-2-inactive.xpm
convert title-3-active.xpm -resize 75% title-3-active.xpm
convert title-3-inactive.xpm -resize 75% title-3-inactive.xpm
convert title-4-active.xpm -resize 75% title-4-active.xpm
convert title-4-inactive.xpm -resize 75% title-4-inactive.xpm
convert title-5-active.xpm -resize 75% title-5-active.xpm
convert title-5-inactive.xpm -resize 75% title-5-inactive.xpm
convert top-left-active.xpm -resize 75% top-left-active.xpm
convert top-left-inactive.xpm -resize 75% top-left-inactive.xpm
convert top-right-active.xpm -resize 75% top-right-active.xpm
convert top-right-inactive.xpm -resize 75% top-right-inactive.xpm
